/**
 * Extracts the Phosphor (MIT) "regular" icons the viewer uses into src/viewer/icons.ts so the bundle and every
 * export stay offline and dependency-free at runtime. Usage: npx tsx scripts/build-icons.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const NAMES = ["map-trifold", "squares-four", "path", "flow-arrow", "app-window", "cards", "tabs", "list-numbers", "caret-left", "caret-right", "caret-down", "caret-up", "arrow-left", "magnifying-glass", "eye", "presentation", "play", "plus", "minus", "corners-out", "x", "check", "code", "file-code", "warning", "link-break", "sidebar-simple", "arrow-u-up-left", "image", "arrow-square-out", "git-branch", "sign-in", "sign-out", "textbox", "cursor-click", "list-bullets", "folder-simple", "stack", "arrows-out-cardinal", "dots-three", "lightning", "funnel", "hash", "keyboard", "link", "question", "prohibit", "arrow-right", "arrow-bend-down-right", "circle", "circle-dashed"];

// the package exports map hides package.json from resolve(); the install location is fixed anyway
const pkgDir = join(process.cwd(), "node_modules", "@phosphor-icons", "core");
const paths: Record<string, string> = {};
for (const name of NAMES) {
  const svg = readFileSync(join(pkgDir, "assets", "regular", `${name}.svg`), "utf8");
  const d = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]).join(" ");
  if (!d) throw new Error(`no path in ${name}`);
  paths[name] = d;
}
const out = `// Generated by scripts/build-icons.ts from @phosphor-icons/core (MIT). Do not edit by hand.
export type IconName = ${NAMES.map((n) => JSON.stringify(n)).join(" | ")};
export const ICON_PATHS: Record<IconName, string> = ${JSON.stringify(paths, null, 0)};
const SVG_NS = "http://www.w3.org/2000/svg";
/** Inline HTML icon (currentColor). Phosphor draws on a 256 grid. */
export function iconHtml(name: IconName, size = 16, cls = "ph"): string {
  return \`<svg class="\${cls}" width="\${size}" height="\${size}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="\${ICON_PATHS[name]}"/></svg>\`;
}
/** Icon as an SVG element for the canvas (fill inherits from the parent's \`fill\`). */
export function iconSvg(name: IconName, x: number, y: number, size = 14, cls = "ph"): SVGGElement {
  const g = document.createElementNS(SVG_NS, "g"); g.setAttribute("class", cls); g.setAttribute("transform", \`translate(\${x},\${y}) scale(\${size / 256})\`);
  const p = document.createElementNS(SVG_NS, "path"); p.setAttribute("d", ICON_PATHS[name]); g.append(p); return g;
}
`;
writeFileSync("src/viewer/icons.ts", out);
console.log(`icons → src/viewer/icons.ts (${NAMES.length} icons, ${Math.round(out.length / 1024)} KB)`);
